# Generated by Django 3.1.7 on 2021-04-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='user',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasker.user'),
        ),
    ]
